### ISSUE TITLE
Module Does not show in the admin

### ISSUE THREAD

**Issue by razarehman56** [durexlovesex/module-cart-popup#1]
Hi,
I have installed this module on magento 2.3.3 and this module does not work and gives issues related to the swatches css & js. Even it does not show in the admin.

**Comment by mekedron** [comment]
@razarehman56 there is no anything added to the admin part. The extension is mostly for developers to show them how this solution can be used for creating this add to cart popup. It seems like it has some conflicts with your custom theme and that is why you're getting the issues. Also I've not tested it with new Magento versions, so I cannot guaranty it will be working with newest versions.
